ROOT_DIR: datasets
MODEL_DIR: models
NUM_PROJECTION_LAYERS: 1
PROJECTION_DIMS: 256
DROPOUT_RATE: 0.1
TRAINABLE_BASE_ENCODERS: false
LEARNING_RATE: 0.001
WEIGHT_DECAY: 0.001
TEMPERATURE: 0.05
NUM_EPOCHS: 5
BATCH_SIZE: 256
K: 9